[tool.briefcase]
project_name = "Appinfantil"
bundle = "org.pybee.appinfantil"
version = "0.1"

[tool.briefcase.app.appinfantil]
formal_name = "AppInfantil"
description = "My first Briefcase App"
sources = ['App-Infantil-main/src/appinfantil']